[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = '''
  let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
hook_add = '''
  nmap <silent> gd <Plug>(coc-definition)
  nmap <silent> gy <Plug>(coc-type-definition)
  nmap <silent> gi <Plug>(coc-implementation)
  nmap <silent> gr <Plug>(coc-references)
  nmap <silent> <space>rn <Plug>(coc-rename)
  nmap <silent> <space>fmt <Plug>(coc-format)
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  nnoremap <C-n> :NERDTree<CR>
  nnoremap <C-t> :NERDTreeToggle<CR>
  nnoremap <C-f> :NERDTreeFind<CR>
  nnoremap <C-m> :NERDTreeFocus<CR>
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
  \ 'colorscheme': 'elly',
  \ 'separator': {
  \   'left': "\ue0b0", 
  \   'right': "\ue0b2"
  \ },
  \ 'subseparator': {
  \   'left': "\ue0b1",
  \   'right': "\ue0b3"
  \ },
  \ 'active': {
  \   'left': [['mode'], ['gitbranch', 'readonly', 'filename'],['coc_status']],
  \   'right': [['lineinfo'], ['percent'], ['filetype']]
  \ },
  \ 'component_function': {
  \   'gitbranch': 'gina#component#repo#branch',
  \   'coc_status': 'coc#status',
  \ },
  \ 'tabline': {
  \   'left': [['buffers']],
  \   'right': [['close']],
  \ },
  \ 'component_expand': {
  \   'buffers': 'lightline#bufferline#buffers'
  \ },
  \ 'component_type': {
  \   'buffers': 'tabsel',
  \ },
  \ }

'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  let g:gitgutter_sign_added = "\uf067"
  let g:gitgutter_sign_modified = "\uf054"
  let g:gitgutter_sign_removed = "\uf00d"
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'ulwlu/elly.vim'

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'mengelbrecht/lightline-bufferline'
hook_add = '''
  nnoremap <silent>, :bprev<CR>
  nnoremap <silent>. :bnext<CR>
  let g:lightline#bufferline#show_number=2
  let g:lightline#bufferline#unnamed='[No Name]'
  let g:lightline#bufferline#enable_devicons=1 
  let g:lightline#bufferline#unicode_symbols=1
  let g:lightline#bufferline#min_buffer_count=1
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

[[plugins]]
repo = 'yuki-yano/fzf-preview.vim'

