[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = '''
  let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
hook_add = '''
  nmap <silent> gd <Plug>(coc-definition)
  nmap <silent> gy <Plug>(coc-type-definition)
  nmap <silent> gi <Plug>(coc-implementation)
  nmap <silent> gr <Plug>(coc-references)
  nmap <silent> <space>rn <Plug>(coc-rename)
  nmap <silent> <space>fmt <Plug>(coc-format)
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  nnoremap <leader>n :NERDTreeFocus<CR>
  nnoremap <C-n> :NERDTree<CR>
  nnoremap <C-t> :NERDTreeToggle<CR>
  nnoremap <C-f> :NERDTreeFind<CR>
  nnoremap <C-m> :NERDTreeFocus<CR>
'''

[[plugins]]
repo = 'josa42/vim-lightline-coc'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
  \ 'colorscheme': 'elly',
  \ 'separator': {
  \   'left': "\ue0b0", 
  \   'right': "\ue0b2"
  \ },
  \ 'subseparator': {
  \   'left': "\ue0b1",
  \   'right': "\ue0b3"
  \ },
  \ 'active': {
  \   'left': [['mode'], ['gitbranch', 'readonly', 'filename', 'modified'], ['coc_status']],
  \ },
  \ 'component_function': {
  \   'gitbranch': 'FugitiveHead'
  \ },
  \}

  let g:lightline.component_expand = {
  \ 'linter_ok': 'lightline#coc#ok',
  \ 'status': 'lightline#coc#status',
  \ }

  let g:lightline.component_type = {
  \ 'linter_ok': 'left',
  \ }

  let g:lightline.active = {
  \ 'right': [['coc_ok'], ['lineinfo'], ['percent'], ['filetype']]
  \ }
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'rakr/vim-one'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  let g:gitgutter_sign_added = "\uf067"
  let g:gitgutter_sign_modified = "\uf054"
  let g:gitgutter_sign_removed = "\uf00d"
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'sainnhe/sonokai'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'ulwlu/elly.vim'

