[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = '''
  let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
hook_add = '''
  nmap <silent> gd <Plug>(coc-definition)
  nmap <silent> gy <Plug>(coc-type-definition)
  nmap <silent> gi <Plug>(coc-implementation)
  nmap <silent> gr <Plug>(coc-references)
  nmap <silent> <space>rn <Plug>(coc-rename)
  nmap <silent> <space>fmt <Plug>(coc-format)
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  nnoremap <leader>n :NERDTreeFocus<CR>
  nnoremap <C-n> :NERDTree<CR>
  nnoremap <C-t> :NERDTreeToggle<CR>
  nnoremap <C-f> :NERDTreeFind<CR>
  nnoremap <C-m> :NERDTreeFocus<CR>
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
  \ 'colorscheme': 'elly',
  \ 'separator': {
  \   'left': "\ue0b0", 
  \   'right': "\ue0b2"
  \ },
  \ 'subseparator': {
  \   'left': "\ue0b1",
  \   'right': "\ue0b3"
  \ },
  \ 'active': {
  \   'left': [['mode'], ['gitbranch', 'readonly', 'filename', 'modified'],['coc_status']],
  \   'right': [['lineinfo'], ['percent'], ['filetype']]
  \ },
  \ 'component_function': {
  \   'gitbranch': 'gina#component#repo#branch',
  \   'coc_status': 'coc#status',
  \   'bufferinfo': 'lightline#buffer#bufferinfo'
  \ },
  \ 'tabline': {
  \   'left': [ [ 'bufferinfo' ],
  \             [ 'separator' ],
  \             [ 'bufferbefore', 'buffercurrent', 'bufferafter' ], ],
  \   'right': [ [ 'close' ], ],
  \ },
  \ 'component_expand': {
  \   'buffercurrent': 'lightline#buffer#buffercurrent',
  \   'bufferbefore': 'lightline#buffer#bufferbefore',
  \   'bufferafter': 'lightline#buffer#bufferafter',
  \ },
  \ 'component_type': {
  \   'buffercurrent': 'tabsel',
  \   'bufferbefore': 'raw',
  \   'bufferafter': 'raw',
  \ },
  \ 'component': {
  \   'separator': '',
  \ },
  \ }

'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'rakr/vim-one'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  let g:gitgutter_sign_added = "\uf067"
  let g:gitgutter_sign_modified = "\uf054"
  let g:gitgutter_sign_removed = "\uf00d"
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'sainnhe/sonokai'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'ulwlu/elly.vim'

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'mengelbrecht/lightline-bufferline'
hook_add = '''
  nnoremap <silent>, :bprev<CR>
  nnoremap <silent>. :bnext<CR>
  let g:lightline_buffer_enable_devicons = 1
  let g:lightline_buffer_show_bufnr = 1
  let g:lightline_buffer_fname_mod = ':t'
  let g:lightline_buffer_excludes = ['vimfiler']
  let g:lightline_buffer_maxflen = 30
  let g:lightline_buffer_maxfextlen = 3
  let g:lightline_buffer_minflen = 16
  let g:lightline_buffer_minfextlen = 3
  let g:lightline_buffer_reservelen = 20
'''

