[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = '''
  let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
hook_add = '''
  nmap <silent> gd <Plug>(coc-definition)
  nmap <silent> gy <Plug>(coc-type-definition)
  nmap <silent> gi <Plug>(coc-implementation)
  nmap <silent> gr <Plug>(coc-references)
  nmap <leader>rn <Plug>(coc-rename)
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  nnoremap <leader>n :NERDTreeFocus<CR>
  nnoremap <C-n> :NERDTree<CR>
  nnoremap <C-t> :NERDTreeToggle<CR>
  nnoremap <C-f> :NERDTreeFind<CR>
  nnoremap <C-m> :NERDTreeFocus<CR>
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline_theme = 'one'
  let g:airline_powerline_fonts = 1
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#hunks#enabled = 0
  let g:airline_section_z = airline#section#create(['windowswap', '%3p%% ', 'linenr', ':%3v'])
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'rakr/vim-one'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'sainnhe/edge'

